syntax = "proto3";

package product;

service ProductService {
  rpc Create (CreateProductRequest) returns (Product);
  rpc FindAll (Empty) returns (ProductList);
  rpc FindOne (ProductById) returns (Product);
  rpc Update (UpdateProductRequest) returns (Product);
  rpc Remove (ProductById) returns (DeleteProductResponse);
}

message Empty {}

message Product {
  string id = 1;
  string name = 2;
  string description = 3;
  double price = 4;
}

message ProductList {
  repeated Product items = 1;
}

message ProductById {
  string id = 1;
}

message CreateProductRequest {
  string name = 1;
  string description = 2;
  double price = 3;
}

message UpdateProductRequest {
  string id = 1;
  optional string name = 2;
  optional string description = 3;
  optional double price = 4;
}

message DeleteProductResponse {
  bool success = 1;
}
